model:
  name: mutaplm
  protein_model: /data_storage/niezk/model/esm/esm2_t33_650M_UR50D
  llama_ckpt: /data_storage/niezk/model/biomedgpt-lm
  num_query_tokens_protein1: 64
  num_query_tokens_protein2: 64
  ca_num_head: 8
  protein_maxlen: 1024
  text_maxlen: 512
  func_maxlen: 256
  system_prompt: You are an expert at biology and life science. Now a user gives you several protein sequences and mutations. Please follow user instructions and answer their questions. Based on the following protein sequence, please describe its function.
  stage2_prompt: Next is a feature of the mutation {} to {} at position {}. Please generate a {} text to describe it.
  text_generation:
    num_beams: 2
    max_length: 256
    min_length: 1
    repetition_penalty: 1.5
    length_penalty: 1
    temperature: 0.2
    do_sample: True
    num_return_sequences: 1